name: Reusable Workflow

on:
  workflow_call:
    inputs:
      greeting:
        description: 'The greeting message'
        required: true
        type: string
      
jobs:
  reusable_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Print ENVNAME
        run: echo "The value of ENVNAME is ${{ secrets.ENVNAME }}"
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v4.2.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      # - name: Package application
      #   run:  mvn package -Dmaven.test.skip=true
      # - name: Build with Maven
      #   run: mvn clean install
      #   working-directory: ./myspringbootapp/simple-springboot-app/

      # - name: Run tests
      #   run: mvn test
      #   working-directory: ./myspringbootapp/simple-springboot-app/

      - name: Package application
        run: mvn package -Dmaven.test.skip=true
        working-directory: ./myspringbootapp/simple-springboot-app
      - name: Archive JAR file
        uses: actions/upload-artifact@v4.6.1
        with:
          name: springboot-app
          path: ./myspringbootapp/simple-springboot-app/target/*.jar